version = 1

test_patterns = [
    "tests/**"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
    "requirements/prod.txt"
]
runtime_version = "3.x.x"

  [analyzers.meta]
  max_line_length = 88

[[analyzers]]
name = "test-coverage"
enabled = true
