version = 1

test_patterns = [
    "tests/**",
    "test_*.py"
]

exclude_patterns = [
    "docs/**",
    "setup.py",
    "tests/**",
    "scripts/**",
    "conf/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 88
  skip_doc_coverage = ["module", "magic", "init"]

[[analyzers]]
name = "shell"
enabled = true

  [analyzers.meta]
  dialect = "bash"
