language: python
cache: pip
git:
  quiet: true
python:
  - "3.7"
install:
  - pip install -q -U pip wheel
  - pip install -q -U -e .[test] --upgrade-strategy eager
  - pip install -q -U Sphinx codecov --upgrade-strategy eager
script:
  - pytest --cov-branch --cov=bip tests
  - python setup.py --quiet build_sphinx sdist bdist_wheel
after_success:
  - codecov
