language: python
cache: pip
python:
  - "3.7"
install:
  - pip install -U -r requirements/test.txt
  - pip install -U Sphinx wheel
  - pip install -e .
  - pip install -U codacy-coverage
script:
  - pytest --cov-branch --cov-report xml --cov=bip tests
  - python setup.py --quiet build_sphinx
  - python setup.py --quiet sdist bdist_wheel
after_success:
  - python-codacy-coverage -r coverage.xml
