name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U -q pip
        pip install -U -q -e .[test]
        pip install -U -q Sphinx wheel
    - name: Test with pytest
      run: |
        pytest --cov-branch --cov-report xml --cov bip tests
    - name: Codecov
      if: matrix.python-version == 3.7
      uses: codecov/codecov-action@v1.0.6
      with:
        fail_ci_if_error: true
    - name: Test package build
      run: |
        python setup.py -q sdist bdist_wheel build_sphinx
