name: Release

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Set up Python 3.7
      uses: actions/setup-python@v4.0.0
      with:
        python-version: 3.7
    - name: Get pip cache dir
      id: pip-cache-dir
      run: echo "::set-output name=dir::$(pip cache dir)"
    - name: Cache pip
      uses: actions/cache@v3.0.6
      with:
        path: ${{ steps.pip-cache-dir.outputs.dir }}
        key: pip|3.7|${{ hashFiles('setup.py') }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel setuptools
    - name: Build packages
      run: |
        python setup.py sdist bdist_wheel
    - name: Upload packages to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
