name: Release

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.5.0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.10"
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel setuptools
    - name: Build packages
      run: |
        python setup.py sdist bdist_wheel
    - name: Upload packages to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.5
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
