name: Tests

on: 
  push:
    branches:
      - master
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v3.3.0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel
        pip install -U -e .[test] --upgrade-strategy eager
    - name: Test with pytest
      run: |
        pytest --cov-branch --cov-report xml --cov bip tests
    - name: Coveralls report
      if: matrix.python-version == 3.10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        python -m pip install -U coveralls
        coveralls
